Repository debionetwork/polkadot-provider, pull requests merged in 2022-06, with the labels that each got.

#61 Stake unstake lab fee
  src/command/labs/index.ts
  test/e2e/labs/index.spec.ts
Labels: feature

#62 feat: genetic analyst error handling
  src/command/genetic-analyst/index.ts
  test/unit/command/genetic-analyst/genetic-analysts.command.spec.ts
Labels: enhancement, improvement, feature

#63 feat: update package version v0.0.11
  package.json
Labels: enhancement, ci

#64 feat: implement polkadot extension signer
  package-lock.json
  package.json
  src/command/doctors/certifications.ts
  src/command/doctors/index.ts
  src/command/electronic-medical-record.ts
  src/command/genetic-analyst/genetic-analysis-orders.ts
  src/command/genetic-analyst/genetic-analysis.ts
  src/command/genetic-analyst/genetic-analyst-qualification.ts
  src/command/genetic-analyst/genetic-analyst-services.ts
  src/command/genetic-analyst/genetic-data.ts
  src/command/genetic-analyst/index.ts
  src/command/hospitals/certifications.ts
  src/command/hospitals/index.ts
  src/command/index.ts
  src/command/labs/certifications.ts
  src/command/labs/genetic-testing.ts
  src/command/labs/index.ts
  src/command/labs/orders.ts
  src/command/labs/services.ts
  src/command/rewards.ts
  src/command/service-request.ts
  src/command/user-profile.ts
  src/models/electronic-medical-record/electronic-medical-record-file.ts
  src/models/labs/index.ts
  src/models/labs/orders/index.ts
  src/query/service-request.ts
  test/e2e/labs/index.spec.ts
  test/unit/command/electronic-medical-record/electronic-medical-record.command.spec.ts
  test/unit/command/genetic-analyst/genetic-analysis-orders/genetic-analysis-orders.command.spec.ts
  test/unit/command/genetic-analyst/genetic-analysis/genetic-analysis.command.spec.ts
  test/unit/command/genetic-analyst/genetic-analyst-services/genetic-analyst-services.command.spec.ts
  test/unit/command/genetic-analyst/genetic-data/genetic-data.command.spec.ts
  test/unit/command/labs/genetic-testing/genetic-testing.command.spec.ts
  test/unit/command/labs/labs.command.spec.ts
  test/unit/command/labs/orders/orders.command.spec.ts
  test/unit/command/labs/services/services.command.spec.ts
  test/unit/command/rewards/rewards.command.spec.ts
  test/unit/command/service-request/service-request.command.spec.ts
  test/unit/command/user-profile/user-profile.command.spec.ts
Labels: enhancement, feature

#65 feat: add submit data bounty details command
  package.json
  src/command/index.ts
  src/command/labs/genetic-testing.ts
  test/e2e/labs/genetic-testing.spec.ts
Labels: enhancement, test, improvement, feature
