Repository debionetwork/polkadot-provider, pull requests merged in 2022-12, with the labels that each got.

#85 feat: update model menstrual calendar cycle log and command
  src/command/menstrual-calendar.ts
  src/command/service-request.ts
  src/events/handlers/geneticAnalyst.ts
  src/models/menstrual-calendar/index.ts
  src/models/menstrual-calendar/menstrual-cycle-log.model.ts
Labels: improvement, feature

#86 fix: menstrual subscription properties and service request by order id
  src/command/menstrual-subscription.ts
  src/models/menstrual-subscription/index.ts
  src/primitives/subscription-status.ts
  src/query/service-request.ts
  test/unit/@polkadot-types.mock.ts
  test/unit/query/service-request/service-request.query.mock.ts
  test/unit/query/service-request/service-request.query.spec.ts
Labels: fix, improvement

#87 chore: bump version 0.0.17
  package.json
Labels: improvement
