Repository debionetwork/polkadot-provider, pull requests merged in 2022-10, with the labels that each got.

#80 fix: update finalize request command
  src/command/service-request.ts
  test/unit/command/service-request/service-request.command.spec.ts
Labels: fix, improvement

#78 feat: menstrual calendar command and query
  package-lock.json
  src/command/labs/orders.ts
  src/command/menstrual-calendar.ts
  src/command/menstrual-subscription.ts
  src/command/service-request.ts
  src/events/handlers/customer.ts
  src/events/handlers/geneticAnalyst.ts
  src/models/menstrual-calendar/index.ts
  src/models/menstrual-calendar/menstrual-calendar.model.ts
  src/models/menstrual-calendar/menstrual-cycle-log.model.ts
  src/models/menstrual-calendar/symptom.ts
  src/models/menstrual-subscription/index.ts
  src/models/service-request/index.ts
  src/models/service-request/service-invoice.ts
  src/models/service-request/service-price.ts
  src/primitives/duration.ts
  src/primitives/payment-status.ts
  src/primitives/subscription-status.ts
  src/query/menstrual-calendar.ts
  src/query/menstrual-subscription.ts
  src/query/service-request.ts
  test/e2e/docker-compose.yml
  test/e2e/doctors/index.spec.ts
  test/e2e/jest-e2e.json
  test/e2e/labs/genetic-testing.spec.ts
  test/e2e/labs/index.spec.ts
  test/e2e/labs/orders.spec.ts
  test/e2e/service-request.spec.ts
  test/e2e/setup.ts
  test/e2e/user-profile.spec.ts
  test/unit/command/labs/orders/orders.command.spec.ts
  test/unit/command/service-request/service-request.command.spec.ts
  test/unit/models/labs/services.mock.ts
  test/unit/query/service-request/service-request.query.spec.ts
  yarn.lock
Labels: enhancement, feature

#81 chore: bump version 0.0.15
  package.json
Labels: enhancement
