Repository debionetwork/polkadot-provider, pull requests merged in 2022-11, with the labels that each got.

#82 feat: add service id and order id in service request model
  src/models/service-request/index.ts
  test/e2e/genetic-analysts/index.spec.ts
  test/e2e/service-request.spec.ts
Labels: enhancement, feature

#83 feat: make dynamic currency and adjust balance format on GA notification
  src/events/event-types.ts
  src/events/handlers/geneticAnalyst.ts
Labels: feature

#84 chore: bump version 0.0.16
  package.json
Labels: enhancement
